### ISSUE TITLE
Issue with TensorBoard Kubernetes service not showing anything

### ISSUE THREAD

**Issue by pdeligia** [wbuchwalter/blog-posts#5]
Hi William,

Thanks for the really insightful series of blog posts, they were a great read!

I have successfully deployed a Kubernetes GPU cluster on Azure, and I am able to run ML experiments on it, and store the results in an Azure Storage file share. A typical job that I run is:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    metadata:
      name: job
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: SOME_IMAGE
        command: ["SOME_COMMAND that outputs results to /data"]
        resources:
          limits:
            alpha.kubernetes.io/nvidia-gpu: 1
          requests:
            alpha.kubernetes.io/nvidia-gpu: 1
        volumeMounts:
        - name: libraries
          mountPath: /usr/lib/x86_64-linux-gnu
        - name: azurefile
          mountPath: /data
      volumes:
      - name: libraries
        hostPath:
          path: /usr/lib/x86_64-linux-gnu
      - name: azurefile
        azureFile:
            secretName: AZURE_SECRET
            shareName: data
            readOnly: false
```
I am now trying to deploy a TensorBoard service that visualizes these experiments. To deploy this service, I do:

```
apiVersion: v1
kind: Service
metadata:
  name: tensorboard
  labels:
    app: tensorboard
spec:
  selector:
    app: tensorboard
  type: LoadBalancer
  ports:
  - port: 6006
    targetPort: 6006
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tensorboard
  labels:
    app: tensorboard
spec:
  template:
    metadata:
      labels:
        app: tensorboard
    spec:
      containers:
      - name: tensorboard
        command: ["/bin/sh", "-c"]
        args: ["tensorboard --logdir /data"]
        image: tensorflow/tensorflow
        ports:
        - containerPort: 6006
        volumeMounts:
        - name: azurefile
          mountPath: /data
      volumes:
      - name: azurefile
        azureFile:
            secretName: AZURE_SECRET
            shareName: data
            readOnly: true
```
After doing `kubectl get svc`, I get the external IP of the service.

Now the problem is that when I am trying to go to this IP (with port 6006), I can see that the TensorBoard website is trying to load, but no visuals or anything is showing (basically the browser window is completely empty). I am also getting the following error on the browser:

```
HTTP404: NOT FOUND - The server has not found anything matching the requested URI (Uniform Resource Identifier).
(XHR)GET - http://13.81.112.63:6006/weblas.map.json%3C/script%3E%3Cscript%3E//~~WEBPATH~~external/com_google_javascript_closure_library/closure/goog/base.js
```

Do you have some advise regarding this? I can provide more information if required.

Thanks a lot,
Pantazis
